### ISSUE TITLE
Found another feedback for you

### ISSUE THREAD

**Issue by tommai78101** [kroitor/gjk.c#4]
Randy Gaul, game engine developer, gave another feedback on your code.

Please take a look here:

https://www.reddit.com/r/gamedev/comments/6wivay/gilbertjohnsonkeerthi_gjk_collision_detection/dm9g3mk/

**Comment by kroitor** [comment]
@tommai78101, thanks! 

Though, most commenters see this as an example of old school code with a readme (*"code first, readme second"*), the actual purpose of the repository is actually educational (readme first, code second). The code itself is made to look like old-school c intentionally, to be easily understandable, not to show off latest compiler features nor newest language keywords/practices, of course. 

The goal of the repo is to help people understand GJK, it does not pretend to be the one and only way to name it and implement it. I will be happy if my text helps someone, even if nobody actually uses my code (which I would not recommend to use without having understood the algorithm in the first place).

Of course, I saw all implementations, including the docs of Erin Catto, and others. I've read them all multiple times. But again, my goal was not to be technically precise, but to be newb-friendly. People don't always want strict terminology and complex code. It's not an academically-sound scientific article, instead, I wanted GJK to be available to everyone so that everybody could play with it on their back yard...

Thx again!

**Comment by RandyGaul** [comment]
Cross posting from reddit:

Sure that makes total sense :)

Though I have run into all these precision problems I am vaguely referring to in my own games and side projects. These aren't just scientific concerns; those problems arise in actual day to day games.

I setup a test to overlay two triangles and jostle the vertices with random perturbations. This is an example of something quite typical for a 2D game. There were an alarming number of failures. I submit a pull request so you can check this out.

Also I would suggest tracking your iteration count and look for cases where iteration count spikes. You may find it a good idea to cap the maximum number of iterations and return a failure if you hit the cap (perhaps 50 iterations or some arbitrary number).
